--- 
driver: 
  name: vagrant 

provisioner: 
  hosts: test-kitchen 
  name: ansible_playbook 
  roles_path: roles 
  require_ansible_repo: true 
  ansible_verbose: true 
  ansible_version: latest 
  require_chef_for_busser: false
  playbook: website-https.yml 

verifier: 
  name: inspec 

platforms: 
  - name: ubuntu-20.04 

suites: 
  - name: default 
    verifier: 
      inspec_tests: 
        - path: tests/profile.rb
