- hosts: myhost 
  remote_user: root
  become: yes
  tasks: 
    - name: Fix SSL in Apache 
      replace: dest=/etc/apache2/mods-available/ssl.conf 
        regexp='^SSLProtocol.*$' 
        replace='SSLProtocol -all +TLSv1.2' 
      notify: 
        - Restart apache2 
        - Restart sshd
  handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: apache2
        state: restarted

    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted 
