---
#  - hosts: test-kitchen
  - hosts: myhost
    remote_user: root
    become: yes
    vars:
      conftext: |
        <VirtualHost *:80>
         DocumentRoot "/var/www/helloworld"
          <Directory "/var/www/helloworld">
            allow from all
            Options None
            Require all granted
          </Directory>
        </VirtualHost>
    tasks:
    - name: "Update apt cache"
      apt: update_cache=true

    - name: Install specific version of apache2
      apt:
        name: apache2=2.4.41-4ubuntu3.8

    - name: Install curl if it doesn't exist
      apt:
        name: curl
        state: latest

    - name: Configure Hello World virtual host
      copy:
        content: "{{ conftext }}"
        dest: /etc/apache2/sites-available/helloworld.conf
        mode: 0640
        force: yes

    - name: Create the helloworld directory
      file:
        path: /var/www/helloworld
        state: directory
        mode: 0755

    - name: Deploy the Hello World website
      copy: 
        src: ./index.html
        dest: /var/www/helloworld/index.html
        owner: root
        group: root
        mode: 0644
        force: yes

    - name: Deactivate the default virtualhost
      command: a2dissite 000-default

    - name: Activate the virtualhost
      command: a2ensite helloworld 
      notify:
        - Restart apache
    
    handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: apache2
        state: restarted
